const ACCEPTANCE_STATE_NAME = "acceptanceState";
const INITIAL_STATE_NAME = "initialState";

const LAMBDA_TRANSITION_LABEL = "ε";

export { INITIAL_STATE_NAME, ACCEPTANCE_STATE_NAME, LAMBDA_TRANSITION_LABEL };
